# Generated by Django 3.0 on 2020-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_Id', models.CharField(max_length=100)),
                ('lead_Name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('contactSource', models.CharField(choices=[('Phone', 'Phone'), ('E-mail', 'E-mail'), ('Direct Meeting', 'Direct Meeting')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadId', models.CharField(max_length=100)),
                ('leadName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone1', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Open-Attempted to Contact', 'Open-Attempted to Contact'), ('Open-In Contact', 'Open-In Contact'), ('Closed-Succesfully', 'Closed-Succesfully'), ('Closed-Not Relevant', 'Closed-Not Relevant')], max_length=30)),
                ('picture', models.ImageField(upload_to='images')),
                ('company', models.CharField(max_length=200)),
                ('contactPerson', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('leadRegisterDate', models.DateField(null=True)),
                ('phone2', models.CharField(max_length=100)),
                ('websiteAddress', models.CharField(max_length=250)),
                ('leadSource', models.CharField(max_length=200)),
                ('leadIndustry', models.CharField(max_length=100)),
                ('leadType', models.CharField(choices=[('Architecture Consultant', 'Architecture Consultant'), ('Client', 'Client')], max_length=30)),
                ('officeAddress', models.CharField(max_length=200)),
                ('additionalNotes', models.CharField(max_length=200)),
            ],
        ),
    ]
