# Generated by Django 3.0 on 2020-10-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdologin', '0002_auto_20201020_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='lead_name',
            new_name='lead_Name',
        ),
    ]
